//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public string imageId { get; set; }
        public string imageName { get; set; }
        public Nullable<double> timeShoot { get; set; }
        public string userId { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual EngResult EngResult { get; set; }
        public virtual User User { get; set; }
        public virtual VieResult VieResult { get; set; }
    }
}
